# Generated by Django 2.2.5 on 2019-10-18 10:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapServices',
            fields=[
                ('service_id', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Service ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('service_attribution', models.CharField(max_length=255, verbose_name='Service Attribution')),
                ('service_url', models.CharField(max_length=255, verbose_name='WMS URL')),
                ('publish', models.BooleanField(default=False, verbose_name='Publish')),
            ],
        ),
        migrations.CreateModel(
            name='LayerServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255, verbose_name='Layer Name')),
                ('publish', models.BooleanField(default=False, verbose_name='Publish')),
                ('map_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapservice.MapServices')),
            ],
        ),
    ]
