# Generated by Django 2.2.5 on 2019-10-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerservices',
            name='layer_display_name',
            field=models.CharField(default='as', max_length=255, verbose_name='Layer Display Name'),
            preserve_default=False,
        ),
    ]
