# Generated by Django 2.2.5 on 2019-10-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapservice', '0002_layerservices_layer_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerservices',
            name='publish',
        ),
    ]
