# Generated by Django 2.2.5 on 2019-10-18 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapservice', '0003_remove_layerservices_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerservices',
            name='map_services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layerservices', to='mapservice.MapServices'),
        ),
    ]
