# Generated by Django 2.2.5 on 2019-10-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapservice', '0004_auto_20191018_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerservices',
            name='map_services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layerservices', to='mapservice.MapServices', verbose_name='Map Service'),
        ),
    ]
