# Generated by Django 2.2.5 on 2019-10-11 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ODKConnector',
            fields=[
                ('con_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Connection ID')),
                ('con_nama', models.CharField(max_length=255, verbose_name='Connection Name')),
                ('db_username', models.CharField(max_length=255, verbose_name='DB Username')),
                ('db_password', models.CharField(max_length=255, verbose_name='DB Username')),
                ('db_host', models.CharField(max_length=255, verbose_name='DB HOST')),
                ('db_port', models.PositiveIntegerField(default=5432, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='DB PORT')),
                ('db_name', models.CharField(max_length=255, verbose_name='DB Name')),
                ('db_schema', models.CharField(max_length=255, verbose_name='DB Schema')),
                ('odk_table_name', models.CharField(max_length=255, verbose_name='ODK Table Name')),
                ('geometry_column', models.CharField(max_length=255, verbose_name='Geometry Column')),
                ('geometry_type', models.CharField(choices=[('point', 'point'), ('polyline', 'polyline'), ('polygon', 'polygon')], max_length=255, verbose_name='Geometry Type')),
            ],
            options={
                'verbose_name_plural': 'ODK Connection',
                'ordering': ['pk'],
                'get_latest_by': 'pk',
            },
        ),
    ]
