# Generated by Django 2.2.5 on 2019-10-11 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odkcollect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odkconnector',
            name='con_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Connection ID'),
        ),
        migrations.AlterField(
            model_name='odkconnector',
            name='db_host',
            field=models.CharField(default='localhost', max_length=255, verbose_name='DB HOST'),
        ),
        migrations.AlterField(
            model_name='odkconnector',
            name='db_password',
            field=models.CharField(max_length=255, verbose_name='DB Password'),
        ),
    ]
