# Generated by Django 2.2.5 on 2019-10-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odkcollect', '0002_auto_20191011_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='odkconnector',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
    ]
