# Generated by Django 2.2.5 on 2019-10-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odkcollect', '0003_odkconnector_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='odkconnector',
            name='latitude_column',
            field=models.CharField(blank=True, help_text='Kolom Geometri untuk titik', max_length=255, null=True, verbose_name='Latitude Column'),
        ),
        migrations.AddField(
            model_name='odkconnector',
            name='longitude_column',
            field=models.CharField(blank=True, help_text='Kolom Geometri untuk titik', max_length=255, null=True, verbose_name='Longitude Column'),
        ),
        migrations.AlterField(
            model_name='odkconnector',
            name='geometry_column',
            field=models.CharField(blank=True, help_text='Kolom Geometri untuk Garis dan Poligon', max_length=255, null=True, verbose_name='Geometry Column'),
        ),
    ]
