# Generated by Django 2.2.5 on 2019-10-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odkcollect', '0004_auto_20191013_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odkconnector',
            name='geometry_column',
        ),
        migrations.AddField(
            model_name='odkconnector',
            name='polygon_column',
            field=models.CharField(blank=True, help_text='Kolom Geometri untuk Poligon', max_length=255, null=True, verbose_name='Polygon Column'),
        ),
        migrations.AddField(
            model_name='odkconnector',
            name='polyline_column',
            field=models.CharField(blank=True, help_text='Kolom Geometri untuk Garis', max_length=255, null=True, verbose_name='Polyline Column'),
        ),
    ]
