# Generated by Django 2.2.5 on 2019-10-16 08:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odkcollect', '0006_auto_20191015_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='odkconnector',
            name='object_color',
            field=colorfield.fields.ColorField(default='#213693', max_length=18, verbose_name='Object Color'),
        ),
    ]
