# Generated by Django 2.2.5 on 2019-10-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odkcollect', '0007_odkconnector_object_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odkconnector',
            name='image_column',
        ),
        migrations.AddField(
            model_name='odkconnector',
            name='geopoint_image',
            field=models.CharField(blank=True, help_text='Kolom untuk gambar, apabila lebih dari satu, gunakan (;) sebagai pemisah', max_length=255, null=True, verbose_name='Geopoint Image Column'),
        ),
        migrations.AddField(
            model_name='odkconnector',
            name='geoshape_image',
            field=models.CharField(blank=True, help_text='Kolom untuk gambar, apabila lebih dari satu, gunakan (;) sebagai pemisah', max_length=255, null=True, verbose_name='Geoshape Image Column'),
        ),
        migrations.AddField(
            model_name='odkconnector',
            name='geotrace_image',
            field=models.CharField(blank=True, help_text='Kolom untuk gambar, apabila lebih dari satu, gunakan (;) sebagai pemisah', max_length=255, null=True, verbose_name='Geotrace Image Column'),
        ),
    ]
