# Generated by Django 2.2.5 on 2019-10-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odkcollect', '0008_auto_20191017_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odkconnector',
            name='geopoint_column',
        ),
        migrations.RemoveField(
            model_name='odkconnector',
            name='geopoint_image',
        ),
        migrations.RemoveField(
            model_name='odkconnector',
            name='geoshape_column',
        ),
        migrations.RemoveField(
            model_name='odkconnector',
            name='geoshape_image',
        ),
        migrations.RemoveField(
            model_name='odkconnector',
            name='geotrace_column',
        ),
        migrations.RemoveField(
            model_name='odkconnector',
            name='geotrace_image',
        ),
        migrations.AddField(
            model_name='odkconnector',
            name='geometry_column',
            field=models.CharField(blank=True, help_text='Kolom Geometri', max_length=255, null=True, verbose_name='Geometry Column'),
        ),
        migrations.AddField(
            model_name='odkconnector',
            name='geometry_image',
            field=models.CharField(blank=True, help_text='Kolom untuk gambar, apabila lebih dari satu, gunakan ( ; ) sebagai pemisah', max_length=255, null=True, verbose_name='Image Column'),
        ),
        migrations.AddField(
            model_name='odkconnector',
            name='group_column',
            field=models.CharField(blank=True, help_text='Kolom Group', max_length=255, null=True, verbose_name='Group Column'),
        ),
    ]
