# Generated by Django 2.2.5 on 2019-10-10 10:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Polygon')),
                ('luas', models.DecimalField(blank=True, decimal_places=4, help_text='dalam kilometer persegi', max_digits=12, null=True, verbose_name='Luas')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
            ],
            options={
                'verbose_name_plural': 'Desa',
                'ordering': ['pk'],
                'get_latest_by': 'pk',
            },
        ),
    ]
