# Generated by Django 2.2.5 on 2019-10-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odkcollect', '0002_auto_20191011_1123'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('odk_connections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odkcollect.ODKConnector', verbose_name='ODK Conncetions List ID')),
            ],
            options={
                'verbose_name_plural': 'Category',
                'ordering': ['pk'],
                'get_latest_by': 'pk',
            },
        ),
    ]
