# Generated by Django 2.2.5 on 2019-10-18 01:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191011_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntensitasGempa',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Polygon')),
                ('luas', models.DecimalField(blank=True, decimal_places=4, help_text='dalam meter persegi', max_digits=12, null=True, verbose_name='Luas')),
                ('value', models.DecimalField(blank=True, decimal_places=4, help_text='dalam SR', max_digits=12, null=True, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='RendamanBanjir',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Polygon')),
                ('luas', models.DecimalField(blank=True, decimal_places=4, help_text='dalam meter persegi', max_digits=12, null=True, verbose_name='Luas')),
            ],
        ),
        migrations.CreateModel(
            name='SesarLembang',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('polyline', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326, verbose_name='Polyline')),
            ],
        ),
    ]
