# Generated by Django 2.2.5 on 2019-10-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191018_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desa',
            name='luas',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='dalam kilometer persegi', max_digits=25, null=True, verbose_name='Luas'),
        ),
        migrations.AlterField(
            model_name='intensitasgempa',
            name='luas',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='dalam meter persegi', max_digits=25, null=True, verbose_name='Luas'),
        ),
        migrations.AlterField(
            model_name='rendamanbanjir',
            name='luas',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='dalam meter persegi', max_digits=25, null=True, verbose_name='Luas'),
        ),
    ]
