# Generated by Django 2.2.5 on 2019-10-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20191019_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunanosm',
            name='exposure_index',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Exposure Index'),
        ),
        migrations.AddField(
            model_name='bangunanosm',
            name='flood_depth',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Flood Depth'),
        ),
    ]
